print('Curriculum Vitae')
print('Sobuleac Catalina')
print('Str.Lesecico,10,ap.53,mun.Balti,Republica Moldova')
print('Date de contact: 023173934')
print('069564135')
print('catalinasobuleac@gmail.com')
print('Data nasterii: 13.01.2005')
print('Nationalitatea: moldoveanca')
print('Locul de munca: Institutia Publica Liceul Teoretic ,,Mihai Eminescu"')
print('Experienta: - ')
print('Educatie si formare: 2020- prezent: Institutia Publica Liceul Teoretic ,,Mihai Eminescu"2')
print('2011-2020: Liceul Teoretic ,, Vasile Alecsandri", mun.Balti')
print('Excelente : Locul III la Olimpiada Municipala la Geografie 2020')
print('Locul III la Olimpiada Municipala la Informatica 2020')
print('Mentiune la Olimpiada Municipala la Biologie 2020')
print('Mentiune la Olimpiada Municipala la Matematica 2020')
print('Mentiune la Olimpiada Municipala la Fizica 2020')
print('Locul II la Olimpiada Liceala la Limba si literatura romana 2019')
print('Locul I la Olimpiada Liceala la Matematica 2019')
print('Locul I la Olimpiada Liceala la Informatica 2019')
print('Locul I la Olimpiada Liceala la Fizica 2019')
print('Locul I la Olimpiada Liceala la Geografie 2019')
print('Locul I la Olimpiada Liceala la Chimie 2019')
print('Locul I la Olimpiada Liceala la Limba Engleza 2019')
print('Locul I la Olimpiada Liceala la Biologie 2019')
print('Locul III la Olimpiada Municipala la Fizica 2019')
print('Locul II la Olimpiada Liceala la Matematica 2018')
print('Locul I la Olimpiada Liceala la Fizica 2018')
print('Mentiune la Concursul  de fizica ,,In memoria distinsului pedagog Petru Medvetki" 2018')
print('Locul III la Olimpiada Municipala la Fizica 2018')
print('Locul III la Olimpiada Municipala la Matematica 2018')
print('Locul I la Olimpiada Liceala la Fizica 2017')
print('Locul I la Olimpiada Liceala la Matematica 2017')
print('Locul II la Olimpiada liceala la Matematica 2014')
print('Competente personale: Adaptibilitate ,Empatie si toleranta ,Initiativa si creativitate')
print('Limba materna: romana ')
print('Alte limbi cunoscute: limba engleza ,limba rusa ,limba franceza')
print('Competente de comunicare: competente de solutionare a situatiilor problema; disponibilitate de colaborare cu colegii ,')
print('Alte competente: Invatare si autodezvoltare, comportament si conduita etica in timpul si inafara serviciului')